import * as vscode from "vscode";
import { ProblemInfo, ProblemType } from "./functionCheck";
import { parseFileContent, FunctionInfo } from "./fileCheck";
import * as gitExtension from "../git";
import { getApiKey } from "./secretStorage";

export interface AIFixResult {
  newComment: string;
}

/**
 * 根据问题信息，从源码中重新解析并获取对应函数的完整上下文。
 */
export async function getFunctionContextFromProblem(
  problem: ProblemInfo
): Promise<FunctionInfo> {
  const uri = vscode.Uri.file(problem.filePath);
  const doc = await vscode.workspace.openTextDocument(uri);
  const content = doc.getText();

  const parseResult = parseFileContent(content, problem.filePath);
  if (!parseResult.success) {
    throw new Error(
      `无法解析函数所在文件：${problem.filePath}（${
        parseResult.errorCode ?? "UNKNOWN"
      }）`
    );
  }

  // 优先按 函数签名 + 行号 精确匹配
  let target = parseResult.functions.find(
    (f) =>
      f.functionSignature === problem.functionSignature &&
      f.lineNumber === problem.lineNumber
  );

  if (!target) {
    // 回退：仅按函数签名匹配
    target = parseResult.functions.find(
      (f) => f.functionSignature === problem.functionSignature
    );
  }

  if (!target) {
    throw new Error(
      `在文件中未找到与问题对应的函数：${problem.functionName}（${problem.functionSignature}）`
    );
  }

  return target;
}

/**
 * 简单判断当前注释主要语言：有中文则视为中文，否则默认英文。
 */
function detectLanguageFromComment(comment: string | undefined): "zh" | "en" {
  if (!comment) {
    return "zh";
  }
  return /[\u4e00-\u9fa5]/.test(comment) ? "zh" : "en";
}

/**
 * 从函数签名中提取参数名列表（与函数检查模块保持一致的简化规则）。
 */
function extractParameters(signature: string): string[] {
  const params: string[] = [];
  const match = signature.match(/\(([^)]*)\)/);
  if (!match || !match[1].trim()) {
    return params;
  }

  const paramList = match[1].split(",");
  for (const param of paramList) {
    const trimmed = param.trim();
    if (!trimmed || trimmed === "void") {
      continue;
    }

    const parts = trimmed.split(/\s+/);
    if (parts.length > 0) {
      let paramName = parts[parts.length - 1];
      paramName = paramName.replace(/[\*&]/g, "");
      if (paramName) {
        params.push(paramName);
      }
    }
  }

  return params;
}

/**
 * 轻量修正 Doxygen 注释：补齐缺失的 @brief/@param/@return 标签。
 */
function fixDoxygenComment(rawComment: string, funcInfo: FunctionInfo): string {
  let comment = rawComment || "";

  // 确保是以 /** 开头、*/ 结尾的块注释
  if (!/\/\*\*/.test(comment)) {
    comment = "/**\n" + comment + "\n*/";
  }

  const hasBrief = /@brief\s+\S/.test(comment);
  const hasReturnTag = /@return\s+\S/.test(comment);
  const params = extractParameters(funcInfo.functionSignature);

  const lines = comment.split(/\r?\n/);
  const bodyLines: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("/**") || trimmed === "*/") {
      continue;
    }
    bodyLines.push(line);
  }

  const newLines: string[] = [];
  if (!hasBrief) {
    newLines.push(
      ` * @brief ${
        detectLanguageFromComment(comment) === "zh"
          ? "函数的功能描述（由 AI 自动生成，建议人工审阅）"
          : "Function description generated by AI (please review)."
      }`
    );
  }

  // 确保每个参数都有一行 @param
  const lower = comment.toLowerCase();
  for (const p of params) {
    if (!new RegExp(`@param\\s+${p}\\b`, "i").test(lower)) {
      newLines.push(
        ` * @param ${p} ${
          detectLanguageFromComment(comment) === "zh"
            ? "参数说明（由 AI 自动生成，建议人工审阅）"
            : "Parameter description generated by AI (please review)."
        }`
      );
    }
  }

  const hasReturnValue = !funcInfo.functionSignature.trim().startsWith("void ");
  if (hasReturnValue && !hasReturnTag) {
    newLines.push(
      ` * @return ${
        detectLanguageFromComment(comment) === "zh"
          ? "返回值说明（由 AI 自动生成，建议人工审阅）"
          : "Return value description generated by AI (please review)."
      }`
    );
  }

  const mergedBody =
    newLines.length > 0
      ? bodyLines.join("\n") + "\n" + newLines.join("\n")
      : bodyLines.join("\n");

  return ["/**", mergedBody, "*/"].join("\n");
}

/**
 * 可选：为变更警告问题附带 Git 变更摘要，供 AI 参考。
 * 若 Git 不可用或失败，则返回 undefined。
 */
async function tryGetGitDiffSnippet(
  problem: ProblemInfo
): Promise<string | undefined> {
  try {
    const workspaceFolders = vscode.workspace.workspaceFolders;
    if (!workspaceFolders || workspaceFolders.length === 0) {
      return undefined;
    }

    const gitExtension = vscode.extensions.getExtension("vscode.git");
    if (!gitExtension || !gitExtension.isActive) {
      return undefined;
    }

    const api = gitExtension.exports.getAPI(1);
    if (!api) {
      return undefined;
    }

    const repo = api.getRepository(workspaceFolders[0].uri);
    if (!repo) {
      return undefined;
    }

    // 尝试获取 HEAD~1 与当前工作区的 diff
    // 这里简化处理，仅返回提示信息
    return "函数体相对于上一次提交发生了变更";
  } catch {
    return undefined;
  }
}

/**
 * 构造 OpenAI Chat Completion 格式的用户提示词
 */
function buildUserPrompt(
  problem: ProblemInfo,
  funcInfo: FunctionInfo,
  language: "zh" | "en",
  diffSnippet?: string
): string {
  const problemTypeLabels: Record<number, { zh: string; en: string }> = {
    1: { zh: "参数缺失", en: "Missing parameter documentation" },
    2: { zh: "返回值缺失", en: "Missing return value documentation" },
    3: { zh: "函数功能说明缺失", en: "Missing function description" },
    4: { zh: "内容变更警告", en: "Content change warning" },
  };

  const problemTypeLabel =
    problemTypeLabels[problem.problemType]?.[language] ||
    `${language === "zh" ? "问题类型" : "Problem type"}: ${problem.problemType}`;

  const lang = language === "zh" ? "中文" : "English";

  let prompt = `请根据以下函数信息生成或更新 Doxygen 格式的注释。要求使用${lang}。

文件路径: ${problem.filePath}
函数名: ${problem.functionName}
函数签名: ${problem.functionSignature}
问题类型: ${problemTypeLabel}

函数代码:
\`\`\`c
${funcInfo.functionContent}
\`\`\``;

  if (funcInfo.comment) {
    prompt += `\n\n现有注释:\n\`\`\`\n${funcInfo.comment}\n\`\`\``;
  }

  if (diffSnippet) {
    prompt += `\n\n变更信息: ${diffSnippet}`;
  }

  prompt += `\n\n请生成完整的 Doxygen 格式注释，包含 @brief、@param（如有参数）、@return（如非 void 函数）等必要标签。只返回注释内容，不要包含其他说明文字。`;

  return prompt;
}

/**
 * 带超时的 fetch 请求
 */
async function fetchWithTimeout(
  url: string,
  options: any,
  timeoutMs: number
): Promise<Response> {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const response = await fetch(url, {
      ...options,
      signal: controller.signal,
    });
    clearTimeout(timeoutId);
    return response;
  } catch (error: any) {
    clearTimeout(timeoutId);
    if (error.name === "AbortError") {
      throw new Error(`请求超时（超过 ${timeoutMs / 1000} 秒）`);
    }
    throw error;
  }
}

/**
 * 核心入口：根据单个问题调用外部 AI 接口生成新的注释内容，并做轻量格式校正。
 * 使用 OpenAI Chat Completion API 格式。
 */
export async function generateCommentWithAI(
  problem: ProblemInfo
): Promise<AIFixResult> {
  const config = vscode.workspace.getConfiguration("doc-doctor");

  const enabled = config.get<boolean>("enableAIRefactor", false);
  if (!enabled) {
    throw new Error(
      "AI 修复功能未启用，请在设置中打开 doc-doctor.enableAIRefactor。"
    );
  }

  const endpoint = config.get<string>("ai.endpoint", "");
  // API Key 从 SecretStorage 读取
  const apiKey = (await getApiKey()) || "";
  const model = config.get<string>("ai.model", "gpt-4");
  const temperature = config.get<number>("ai.temperature", 0.7);
  const timeout = config.get<number>("ai.timeout", 60000);

  if (!endpoint || !apiKey) {
    throw new Error(
      "AI 服务未配置完整，请在设置中填写 doc-doctor.ai.endpoint 和 doc-doctor.ai.apiKey。"
    );
  }

  const funcInfo = await getFunctionContextFromProblem(problem);
  const language = detectLanguageFromComment(funcInfo.comment);
  const diffSnippet = await tryGetGitDiffSnippet(problem);

  // 构造 OpenAI Chat Completion 格式的请求
  const systemMessage =
    language === "zh"
      ? "你是一个专业的代码注释生成助手，专门帮助生成符合 Doxygen 规范的函数注释。请根据函数代码和问题类型，生成准确、简洁的注释。"
      : "You are a professional code documentation assistant that helps generate Doxygen-style function comments. Generate accurate and concise comments based on the function code and problem type.";

  const userMessage = buildUserPrompt(problem, funcInfo, language, diffSnippet);

  const openAIPayload = {
    model: model,
    messages: [
      {
        role: "system",
        content: systemMessage,
      },
      {
        role: "user",
        content: userMessage,
      },
    ],
    temperature: Math.max(0, Math.min(2, temperature)), // 确保在 0-2 范围内
  };

  // 检查 fetch 是否可用
  const globalFetch: any = (globalThis as any).fetch;
  if (typeof globalFetch !== "function") {
    throw new Error(
      "当前运行环境不支持 fetch，请在 generateCommentWithAI 中替换为自定义 HTTP 实现。"
    );
  }

  let res: Response;
  try {
    res = await fetchWithTimeout(
      endpoint,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${apiKey}`,
        },
        body: JSON.stringify(openAIPayload),
      },
      timeout
    );
  } catch (error: any) {
    // 网络错误、超时等
    if (error.message.includes("超时")) {
      throw error;
    }
    if (error.message.includes("fetch")) {
      throw new Error(
        `网络连接失败：${error.message}。请检查网络连接和 endpoint 配置。`
      );
    }
    throw new Error(`AI 接口请求失败：${error.message}`);
  }

  if (!res || !res.ok) {
    const status = res?.status ?? 0;
    let errorText = "";
    try {
      errorText = await res.text();
    } catch {
      errorText = "无法读取错误响应";
    }

    // 根据状态码提供更详细的错误信息
    let errorMessage = `AI 接口调用失败，状态码 ${status}`;
    if (status === 401) {
      errorMessage += "：API Key 无效或已过期";
    } else if (status === 403) {
      errorMessage += "：API Key 无权限访问该模型";
    } else if (status === 404) {
      errorMessage += "：接口地址不存在，请检查 endpoint 配置";
    } else if (status === 429) {
      errorMessage += "：请求频率过高，请稍后重试";
    } else if (status >= 500) {
      errorMessage += "：AI 服务端错误，请稍后重试";
    }

    if (errorText) {
      try {
        const errorJson = JSON.parse(errorText);
        if (errorJson.error?.message) {
          errorMessage += `。详细信息：${errorJson.error.message}`;
        } else {
          errorMessage += `。响应：${errorText.substring(0, 200)}`;
        }
      } catch {
        errorMessage += `。响应：${errorText.substring(0, 200)}`;
      }
    }

    throw new Error(errorMessage);
  }

  let data: any;
  try {
    data = await res.json();
  } catch (e) {
    throw new Error("AI 接口返回内容无法解析为 JSON：" + (e as Error).message);
  }

  // 解析 OpenAI Chat Completion 格式的响应
  let rawComment: string | undefined;
  if (data?.choices?.[0]?.message?.content) {
    // OpenAI Chat Completion 格式
    rawComment = data.choices[0].message.content.trim();
  } else if (data?.newComment) {
    // 兼容旧的自定义格式
    rawComment = data.newComment;
  } else if (data?.comment) {
    // 兼容旧字段名
    rawComment = data.comment;
  }

  if (!rawComment || typeof rawComment !== "string") {
    throw new Error(
      "AI 接口返回内容格式不正确。期望 OpenAI Chat Completion 格式（choices[0].message.content）或自定义格式（newComment/comment 字段）。"
    );
  }

  const fixedComment = fixDoxygenComment(rawComment, funcInfo);

  return { newComment: fixedComment };
}

/**
 * 将 AI 生成的注释应用到源码文件中。
 * 
 * @param problem - 问题信息
 * @param newComment - AI 生成的新注释
 * @returns 是否成功应用
 */
export async function applyAIFixToFile(
  problem: ProblemInfo,
  newComment: string
): Promise<boolean> {
  try {
    const uri = vscode.Uri.file(problem.filePath);
    const doc = await vscode.workspace.openTextDocument(uri);
    
    // 获取函数上下文，确定注释位置
    const funcInfo = await getFunctionContextFromProblem(problem);
    const functionLine = funcInfo.lineNumber - 1; // VS Code 行号从 0 开始
    
    // 打开编辑器
    const editor = await vscode.window.showTextDocument(doc);
    
    // 查找函数定义前的注释位置
    // 从函数定义行向上查找，找到最近的注释块
    let commentStartLine = functionLine;
    let commentEndLine = functionLine;
    
    // 向上查找注释块
    for (let i = functionLine - 1; i >= 0; i--) {
      const line = doc.lineAt(i);
      const text = line.text.trim();
      
      // 如果遇到注释结束标记
      if (text === "*/") {
        commentEndLine = i;
        // 继续向上查找注释开始
        for (let j = i - 1; j >= 0; j--) {
          const prevLine = doc.lineAt(j);
          const prevText = prevLine.text.trim();
          if (prevText.startsWith("/**") || prevText.startsWith("/*")) {
            commentStartLine = j;
            break;
          }
        }
        break;
      }
      
      // 如果遇到非空白、非注释的代码行，停止查找
      if (text && !text.startsWith("*") && !text.startsWith("//")) {
        break;
      }
    }
    
    // 格式化新注释（每行前加适当的缩进）
    const indentMatch = doc.lineAt(functionLine).text.match(/^(\s*)/);
    const indent = indentMatch ? indentMatch[1] : "";
    const commentLines = newComment.split(/\r?\n/);
    const formattedComment = commentLines
      .map((line, index) => {
        if (index === 0) {
          // 第一行 /** 使用函数定义的缩进
          return indent + line;
        } else if (index === commentLines.length - 1) {
          // 最后一行 */ 使用函数定义的缩进
          return indent + line;
        } else {
          // 中间行保持原有格式，但确保有 * 前缀
          if (line.trim().startsWith("*")) {
            return indent + line.trim();
          } else {
            return indent + " * " + line.trim();
          }
        }
      })
      .join("\n");
    
    // 确定替换范围
    let replaceRange: vscode.Range;
    if (commentStartLine < functionLine) {
      // 存在旧注释，替换它
      const startPos = new vscode.Position(commentStartLine, 0);
      const endPos = new vscode.Position(
        commentEndLine,
        doc.lineAt(commentEndLine).text.length
      );
      replaceRange = new vscode.Range(startPos, endPos);
    } else {
      // 没有旧注释，在函数定义前插入
      const insertPos = new vscode.Position(functionLine, 0);
      replaceRange = new vscode.Range(insertPos, insertPos);
    }
    
    // 执行编辑
    await editor.edit((editBuilder) => {
      if (commentStartLine < functionLine) {
        // 替换旧注释
        editBuilder.replace(replaceRange, formattedComment + "\n");
      } else {
        // 插入新注释
        editBuilder.insert(replaceRange.start, formattedComment + "\n");
      }
    });
    
    // 保存文件
    await doc.save();
    
    return true;
  } catch (error) {
    console.error("[Doc-Doctor] 应用 AI 修复失败:", error);
    throw error;
  }
}
