import * as vscode from "vscode";
import { ProblemInfo, ProblemType } from "./functionCheck";
import { parseFileContent, FunctionInfo } from "./fileCheck";
import * as gitExtension from "../git";

export interface AIFixResult {
  newComment: string;
}

/**
 * 根据问题信息，从源码中重新解析并获取对应函数的完整上下文。
 */
async function getFunctionContextFromProblem(
  problem: ProblemInfo
): Promise<FunctionInfo> {
  const uri = vscode.Uri.file(problem.filePath);
  const doc = await vscode.workspace.openTextDocument(uri);
  const content = doc.getText();

  const parseResult = parseFileContent(content, problem.filePath);
  if (!parseResult.success) {
    throw new Error(
      `无法解析函数所在文件：${problem.filePath}（${
        parseResult.errorCode ?? "UNKNOWN"
      }）`
    );
  }

  // 优先按 函数签名 + 行号 精确匹配
  let target = parseResult.functions.find(
    (f) =>
      f.functionSignature === problem.functionSignature &&
      f.lineNumber === problem.lineNumber
  );

  if (!target) {
    // 回退：仅按函数签名匹配
    target = parseResult.functions.find(
      (f) => f.functionSignature === problem.functionSignature
    );
  }

  if (!target) {
    throw new Error(
      `在文件中未找到与问题对应的函数：${problem.functionName}（${problem.functionSignature}）`
    );
  }

  return target;
}

/**
 * 简单判断当前注释主要语言：有中文则视为中文，否则默认英文。
 */
function detectLanguageFromComment(comment: string | undefined): "zh" | "en" {
  if (!comment) {
    return "zh";
  }
  return /[\u4e00-\u9fa5]/.test(comment) ? "zh" : "en";
}

/**
 * 从函数签名中提取参数名列表（与函数检查模块保持一致的简化规则）。
 */
function extractParameters(signature: string): string[] {
  const params: string[] = [];
  const match = signature.match(/\(([^)]*)\)/);
  if (!match || !match[1].trim()) {
    return params;
  }

  const paramList = match[1].split(",");
  for (const param of paramList) {
    const trimmed = param.trim();
    if (!trimmed || trimmed === "void") {
      continue;
    }

    const parts = trimmed.split(/\s+/);
    if (parts.length > 0) {
      let paramName = parts[parts.length - 1];
      paramName = paramName.replace(/[\*&]/g, "");
      if (paramName) {
        params.push(paramName);
      }
    }
  }

  return params;
}

/**
 * 轻量修正 Doxygen 注释：补齐缺失的 @brief/@param/@return 标签。
 */
function fixDoxygenComment(rawComment: string, funcInfo: FunctionInfo): string {
  let comment = rawComment || "";

  // 确保是以 /** 开头、*/ 结尾的块注释
  if (!/\/\*\*/.test(comment)) {
    comment = "/**\n" + comment + "\n*/";
  }

  const hasBrief = /@brief\s+\S/.test(comment);
  const hasReturnTag = /@return\s+\S/.test(comment);
  const params = extractParameters(funcInfo.functionSignature);

  const lines = comment.split(/\r?\n/);
  const bodyLines: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("/**") || trimmed === "*/") {
      continue;
    }
    bodyLines.push(line);
  }

  const newLines: string[] = [];
  if (!hasBrief) {
    newLines.push(
      ` * @brief ${
        detectLanguageFromComment(comment) === "zh"
          ? "函数的功能描述（由 AI 自动生成，建议人工审阅）"
          : "Function description generated by AI (please review)."
      }`
    );
  }

  // 确保每个参数都有一行 @param
  const lower = comment.toLowerCase();
  for (const p of params) {
    if (!new RegExp(`@param\\s+${p}\\b`, "i").test(lower)) {
      newLines.push(
        ` * @param ${p} ${
          detectLanguageFromComment(comment) === "zh"
            ? "参数说明（由 AI 自动生成，建议人工审阅）"
            : "Parameter description generated by AI (please review)."
        }`
      );
    }
  }

  const hasReturnValue = !funcInfo.functionSignature.trim().startsWith("void ");
  if (hasReturnValue && !hasReturnTag) {
    newLines.push(
      ` * @return ${
        detectLanguageFromComment(comment) === "zh"
          ? "返回值说明（由 AI 自动生成，建议人工审阅）"
          : "Return value description generated by AI (please review)."
      }`
    );
  }

  const mergedBody =
    newLines.length > 0
      ? bodyLines.join("\n") + "\n" + newLines.join("\n")
      : bodyLines.join("\n");

  return ["/**", mergedBody, "*/"].join("\n");
}

/**
 * 可选：为变更警告问题附带 Git 变更摘要，供 AI 参考。
 * 若 Git 不可用或失败，则返回 undefined。
 */
async function tryGetGitDiffSnippet(
  problem: ProblemInfo
): Promise<string | undefined> {
  try {
    const workspaceFolders = vscode.workspace.workspaceFolders;
    if (!workspaceFolders || workspaceFolders.length === 0) {
      return undefined;
    }

    const gitExtension = vscode.extensions.getExtension("vscode.git");
    if (!gitExtension || !gitExtension.isActive) {
      return undefined;
    }

    const api = gitExtension.exports.getAPI(1);
    if (!api) {
      return undefined;
    }

    const repo = api.getRepository(workspaceFolders[0].uri);
    if (!repo) {
      return undefined;
    }

    // 尝试获取 HEAD~1 与当前工作区的 diff
    // 这里简化处理，仅返回提示信息
    return "函数体相对于上一次提交发生了变更";
  } catch {
    return undefined;
  }
}

/**
 * 核心入口：根据单个问题调用外部 AI 接口生成新的注释内容，并做轻量格式校正。
 */
export async function generateCommentWithAI(
  problem: ProblemInfo
): Promise<AIFixResult> {
  const config = vscode.workspace.getConfiguration("doc-doctor");

  const enabled = config.get<boolean>("enableAIRefactor", false);
  if (!enabled) {
    throw new Error(
      "AI 修复功能未启用，请在设置中打开 doc-doctor.enableAIRefactor。"
    );
  }

  const endpoint = config.get<string>("ai.endpoint", "");
  const apiKey = config.get<string>("ai.apiKey", "");

  if (!endpoint || !apiKey) {
    throw new Error(
      "AI 服务未配置完整，请在设置中填写 doc-doctor.ai.endpoint 和 doc-doctor.ai.apiKey。"
    );
  }

  const funcInfo = await getFunctionContextFromProblem(problem);
  const language = detectLanguageFromComment(funcInfo.comment);
  const diffSnippet = await tryGetGitDiffSnippet(problem);

  const payload = {
    filePath: problem.filePath,
    functionName: problem.functionName,
    functionSignature: problem.functionSignature,
    problemType: problem.problemType,
    existingComment: funcInfo.comment,
    functionBody: funcInfo.functionContent,
    language,
    gitDiff: diffSnippet,
  };

  const globalFetch: any = (globalThis as any).fetch;
  if (typeof globalFetch !== "function") {
    throw new Error(
      "当前运行环境不支持 fetch，请在 generateCommentWithAI 中替换为自定义 HTTP 实现。"
    );
  }

  const res = await globalFetch(endpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify(payload),
  });

  if (!res || !res.ok) {
    const status = res?.status ?? 0;
    const text = res ? await res.text() : "";
    throw new Error(`AI 接口调用失败，状态码 ${status}，响应：${text}`);
  }

  let data: any;
  try {
    data = await res.json();
  } catch (e) {
    throw new Error("AI 接口返回内容无法解析为 JSON：" + (e as Error).message);
  }

  const rawComment: string | undefined = data?.newComment ?? data?.comment;
  if (!rawComment || typeof rawComment !== "string") {
    throw new Error("AI 接口返回内容中未包含 newComment 字段或类型不正确。");
  }

  const fixedComment = fixDoxygenComment(rawComment, funcInfo);

  return { newComment: fixedComment };
}

/**
 * 将 AI 生成的注释应用到源码文件中。
 * 
 * @param problem - 问题信息
 * @param newComment - AI 生成的新注释
 * @returns 是否成功应用
 */
export async function applyAIFixToFile(
  problem: ProblemInfo,
  newComment: string
): Promise<boolean> {
  try {
    const uri = vscode.Uri.file(problem.filePath);
    const doc = await vscode.workspace.openTextDocument(uri);
    
    // 获取函数上下文，确定注释位置
    const funcInfo = await getFunctionContextFromProblem(problem);
    const functionLine = funcInfo.lineNumber - 1; // VS Code 行号从 0 开始
    
    // 打开编辑器
    const editor = await vscode.window.showTextDocument(doc);
    
    // 查找函数定义前的注释位置
    // 从函数定义行向上查找，找到最近的注释块
    let commentStartLine = functionLine;
    let commentEndLine = functionLine;
    
    // 向上查找注释块
    for (let i = functionLine - 1; i >= 0; i--) {
      const line = doc.lineAt(i);
      const text = line.text.trim();
      
      // 如果遇到注释结束标记
      if (text === "*/") {
        commentEndLine = i;
        // 继续向上查找注释开始
        for (let j = i - 1; j >= 0; j--) {
          const prevLine = doc.lineAt(j);
          const prevText = prevLine.text.trim();
          if (prevText.startsWith("/**") || prevText.startsWith("/*")) {
            commentStartLine = j;
            break;
          }
        }
        break;
      }
      
      // 如果遇到非空白、非注释的代码行，停止查找
      if (text && !text.startsWith("*") && !text.startsWith("//")) {
        break;
      }
    }
    
    // 格式化新注释（每行前加适当的缩进）
    const indentMatch = doc.lineAt(functionLine).text.match(/^(\s*)/);
    const indent = indentMatch ? indentMatch[1] : "";
    const commentLines = newComment.split(/\r?\n/);
    const formattedComment = commentLines
      .map((line, index) => {
        if (index === 0) {
          // 第一行 /** 使用函数定义的缩进
          return indent + line;
        } else if (index === commentLines.length - 1) {
          // 最后一行 */ 使用函数定义的缩进
          return indent + line;
        } else {
          // 中间行保持原有格式，但确保有 * 前缀
          if (line.trim().startsWith("*")) {
            return indent + line.trim();
          } else {
            return indent + " * " + line.trim();
          }
        }
      })
      .join("\n");
    
    // 确定替换范围
    let replaceRange: vscode.Range;
    if (commentStartLine < functionLine) {
      // 存在旧注释，替换它
      const startPos = new vscode.Position(commentStartLine, 0);
      const endPos = new vscode.Position(
        commentEndLine,
        doc.lineAt(commentEndLine).text.length
      );
      replaceRange = new vscode.Range(startPos, endPos);
    } else {
      // 没有旧注释，在函数定义前插入
      const insertPos = new vscode.Position(functionLine, 0);
      replaceRange = new vscode.Range(insertPos, insertPos);
    }
    
    // 执行编辑
    await editor.edit((editBuilder) => {
      if (commentStartLine < functionLine) {
        // 替换旧注释
        editBuilder.replace(replaceRange, formattedComment + "\n");
      } else {
        // 插入新注释
        editBuilder.insert(replaceRange.start, formattedComment + "\n");
      }
    });
    
    // 保存文件
    await doc.save();
    
    return true;
  } catch (error) {
    console.error("[Doc-Doctor] 应用 AI 修复失败:", error);
    throw error;
  }
}
