import * as vscode from "vscode";
import { ProblemInfo, ProblemType } from "./functionCheck";
import { parseFileContent, FunctionInfo } from "./fileCheck";
import * as gitExtension from "../git";

export interface AIFixResult {
  newComment: string;
}

/**
 * 根据问题信息，从源码中重新解析并获取对应函数的完整上下文。
 */
async function getFunctionContextFromProblem(
  problem: ProblemInfo
): Promise<FunctionInfo> {
  const uri = vscode.Uri.file(problem.filePath);
  const doc = await vscode.workspace.openTextDocument(uri);
  const content = doc.getText();

  const parseResult = parseFileContent(content, problem.filePath);
  if (!parseResult.success) {
    throw new Error(
      `无法解析函数所在文件：${problem.filePath}（${
        parseResult.errorCode ?? "UNKNOWN"
      }）`
    );
  }

  // 优先按 函数签名 + 行号 精确匹配
  let target = parseResult.functions.find(
    (f) =>
      f.functionSignature === problem.functionSignature &&
      f.lineNumber === problem.lineNumber
  );

  if (!target) {
    // 回退：仅按函数签名匹配
    target = parseResult.functions.find(
      (f) => f.functionSignature === problem.functionSignature
    );
  }

  if (!target) {
    throw new Error(
      `在文件中未找到与问题对应的函数：${problem.functionName}（${problem.functionSignature}）`
    );
  }

  return target;
}

/**
 * 简单判断当前注释主要语言：有中文则视为中文，否则默认英文。
 */
function detectLanguageFromComment(comment: string | undefined): "zh" | "en" {
  if (!comment) {
    return "zh";
  }
  return /[\u4e00-\u9fa5]/.test(comment) ? "zh" : "en";
}

/**
 * 从函数签名中提取参数名列表（与函数检查模块保持一致的简化规则）。
 */
function extractParameters(signature: string): string[] {
  const params: string[] = [];
  const match = signature.match(/\(([^)]*)\)/);
  if (!match || !match[1].trim()) {
    return params;
  }

  const paramList = match[1].split(",");
  for (const param of paramList) {
    const trimmed = param.trim();
    if (!trimmed || trimmed === "void") {
      continue;
    }

    const parts = trimmed.split(/\s+/);
    if (parts.length > 0) {
      let paramName = parts[parts.length - 1];
      paramName = paramName.replace(/[\*&]/g, "");
      if (paramName) {
        params.push(paramName);
      }
    }
  }

  return params;
}

/**
 * 轻量修正 Doxygen 注释：补齐缺失的 @brief/@param/@return 标签。
 */
function fixDoxygenComment(rawComment: string, funcInfo: FunctionInfo): string {
  let comment = rawComment || "";

  // 确保是以 /** 开头、*/ 结尾的块注释
  if (!/\/\*\*/.test(comment)) {
    comment = "/**\n" + comment + "\n*/";
  }

  const hasBrief = /@brief\s+\S/.test(comment);
  const hasReturnTag = /@return\s+\S/.test(comment);
  const params = extractParameters(funcInfo.functionSignature);

  const lines = comment.split(/\r?\n/);
  const bodyLines: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("/**") || trimmed === "*/") {
      continue;
    }
    bodyLines.push(line);
  }

  const newLines: string[] = [];
  if (!hasBrief) {
    newLines.push(
      ` * @brief ${
        detectLanguageFromComment(comment) === "zh"
          ? "函数的功能描述（由 AI 自动生成，建议人工审阅）"
          : "Function description generated by AI (please review)."
      }`
    );
  }

  // 确保每个参数都有一行 @param
  const lower = comment.toLowerCase();
  for (const p of params) {
    if (!new RegExp(`@param\\s+${p}\\b`, "i").test(lower)) {
      newLines.push(
        ` * @param ${p} ${
          detectLanguageFromComment(comment) === "zh"
            ? "参数说明（由 AI 自动生成，建议人工审阅）"
            : "Parameter description generated by AI (please review)."
        }`
      );
    }
  }

  const hasReturnValue = !funcInfo.functionSignature.trim().startsWith("void ");
  if (hasReturnValue && !hasReturnTag) {
    newLines.push(
      ` * @return ${
        detectLanguageFromComment(comment) === "zh"
          ? "返回值说明（由 AI 自动生成，建议人工审阅）"
          : "Return value description generated by AI (please review)."
      }`
    );
  }

  const mergedBody =
    newLines.join("\n") + (bodyLines.length ? "\n" + bodyLines.join("\n") : "");

  return ["/**", mergedBody, "*/"].join("\n");
}

/**
 * 可选：为变更警告问题附带 Git 变更摘要，供 AI 参考。
 * 若 Git 不可用或失败，则返回 undefined。
 */
async function tryGetGitDiffSnippet(
  problem: ProblemInfo
): Promise<string | undefined> {
  if (problem.problemType !== ProblemType.CONTENT_CHANGED) {
    return undefined;
  }

  try {
    const gitExt =
      vscode.extensions.getExtension<gitExtension.GitExtension>("vscode.git");
    if (!gitExt) {
      return undefined;
    }
    const api = gitExt.exports.getAPI(1);
    const repo = api.getRepository(vscode.Uri.file(problem.filePath));
    if (!repo) {
      return undefined;
    }
    const diff = await repo.diffWith("HEAD~1", problem.filePath);
    return diff || undefined;
  } catch {
    return undefined;
  }
}

/**
 * 核心入口：根据单个问题调用外部 AI 接口生成新的注释内容，并做轻量格式校正。
 */
export async function generateCommentWithAI(
  problem: ProblemInfo
): Promise<AIFixResult> {
  const config = vscode.workspace.getConfiguration("doc-doctor");

  const enabled = config.get<boolean>("enableAIRefactor", false);
  if (!enabled) {
    throw new Error(
      "AI 修复功能未启用，请在设置中打开 doc-doctor.enableAIRefactor。"
    );
  }

  const endpoint = config.get<string>("ai.endpoint", "");
  const apiKey = config.get<string>("ai.apiKey", "");

  if (!endpoint || !apiKey) {
    throw new Error(
      "AI 服务未配置完整，请在设置中填写 doc-doctor.ai.endpoint 和 doc-doctor.ai.apiKey。"
    );
  }

  const funcInfo = await getFunctionContextFromProblem(problem);
  const language = detectLanguageFromComment(funcInfo.comment);
  const diffSnippet = await tryGetGitDiffSnippet(problem);

  const payload = {
    filePath: problem.filePath,
    functionName: problem.functionName,
    functionSignature: problem.functionSignature,
    problemType: problem.problemType,
    existingComment: funcInfo.comment,
    functionBody: funcInfo.functionContent,
    language,
    gitDiff: diffSnippet,
  };

  const globalFetch: any = (globalThis as any).fetch;
  if (typeof globalFetch !== "function") {
    throw new Error(
      "当前运行环境不支持 fetch，请在 generateCommentWithAI 中替换为自定义 HTTP 实现。"
    );
  }

  const res = await globalFetch(endpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify(payload),
  });

  if (!res || !res.ok) {
    const status = res?.status ?? 0;
    const text = res ? await res.text() : "";
    throw new Error(`AI 接口调用失败，状态码 ${status}，响应：${text}`);
  }

  let data: any;
  try {
    data = await res.json();
  } catch (e) {
    throw new Error("AI 接口返回内容无法解析为 JSON：" + (e as Error).message);
  }

  const rawComment: string | undefined = data?.newComment ?? data?.comment;
  if (!rawComment || typeof rawComment !== "string") {
    throw new Error("AI 接口返回内容中未包含 newComment 字段或类型不正确。");
  }

  const fixedComment = fixDoxygenComment(rawComment, funcInfo);

  return { newComment: fixedComment };
}
